version: '3.9'
services:
  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - ./.env
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
  sidekiq:
    container_name: sidekiq
    build: .
    env_file:
      - ./.env
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/app
    command: bundle exec sidekiq
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis:/data
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - loyalty-tiers:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - ${PGADMIN_EXPOSED_PORT}:${PGADMIN_PORT}
    depends_on:
      - postgres
volumes:
  redis:
    driver: local
  loyalty-tiers:
